name: Native CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

        include:
          - os: ubuntu-latest
            COMPILER: gcc
            LINKER: gcc

          - os: macos-latest
            COMPILER: clang
            LINKER: clang

          - os: windows-latest
            COMPILER: gcc
            LINKER: gcc

    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
      if: startsWith(matrix.os, 'windows')
      with:
        msystem: MINGW64
        install: make mingw-w64-x86_64-gcc
    - run: ./tests/run_tests_pc.sh
      if: startsWith(matrix.os, 'windows') != true
    - run: msys2 -c './tests/run_tests_pc.sh'
      if: startsWith(matrix.os, 'windows')
