name: Native CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

        include:
          - os: ubuntu-latest
            COMPILER: gcc
            LINKER: gcc

          - os: macos-latest
            COMPILER: clang
            LINKER: clang

    steps:
    - uses: actions/checkout@v2
    - name: Run native builds
      run: ./tests/run_tests_pc.sh
